hackforla/HomeUniteUs

- README.md
Updated ReadMe with links for how to contribute.
> Update ReadMe with how to contribute

- src/App.tsx
- src/components/GuestProfile/GeneralInfo.tsx
- src/components/GuestProfile/GuestCard.tsx
- src/components/GuestProfile/GuestInfo.tsx
- src/components/GuestProfile/Profile.tsx
- src/components/GuestProfile/index.ts
- src/components/HostProfile/GeneralInfo.tsx
- src/components/HostProfile/HostCard.tsx
- src/components/HostProfile/HousePolicies.tsx
- src/components/HostProfile/Profile.tsx
- src/pages/AdminGuestView.tsx
- src/pages/AdminView.tsx
- src/pages/GuestProfile.tsx
- src/pages/HostProfile.tsx
Hello Tyler, here is my first pass at styling the guest component. Didn't want to go too crazy without knowing what you thought. The TS is really challenging, but I think it works okay for this. Let me know your thoughts. Thanks.
> Lo-fi guest component

- src/components/GuestProfile/GeneralInfo.tsx
- src/components/GuestProfile/GuestCard.tsx
- src/components/GuestProfile/GuestInfo.tsx
Here is the restyled page with the guest profile update and the button bar removed
> restyles guest profile page

- app/src/App.tsx
- app/src/pages/About.tsx
- build.sh
carol anne asked me to add some text to the about page
> adds text to about page

- app/src/components/GuestProfile/GeneralInfo.tsx
I have hidden the emails on the guest pages
> hides email on guest profiles

- app/src/pages/AdminView.tsx
- app/src/pages/Demo.tsx
- app/src/pages/style.ts
In the Admin Page, replaced all MUI components and styles using Styled Components, following the pattern used in Demo page.
There may be some overlap in components between Demo and Admin that can be shared, which can perhaps be optimized in later task.
> Admin page styled components

- app/src/components/MUIModal/ConfirmationModal/ConfirmationModal.tsx
- app/src/components/MUIModal/ConfirmationModal/styles.ts
- app/src/components/MUIModal/MUIModal.tsx
- app/src/components/MUIModal/MessageModal/MessageModal.tsx
- app/src/components/ProfileEdit/QuestionPage.tsx
I just need to fix the styling
> Confirmation modal

- app/src/components/ProfileEdit/QuestionPage.tsx
> progress bar uniformly spaced

- app/src/components/ProfileEdit/QuestionPage.tsx
- app/src/components/Registration/theme.ts
- app/src/pages/ProfileEdit.tsx
I added the rest of the host questions to the test set and found some things that still need work.
- decide on data model
- components needed for Question component
- date from MUI
- image upload
- dropdown from component library
- searchable dropdown list from MUI
- predictive language dropdown?
- family member - do we need every family member's name and gender?
- it would be easier to just ask how many people live there
- if we need to create questions, then we have more work to do
- create question without id
- when saving, back-end can insert new questions that don't have an id and send back new id so they're updated on next save
- set max number of family members
- contact preference in order (Bonnie said this is important)
- primary contact email/phone
- other contact
- other …
> updated host questions

- app/src/components/ProfileEdit/QuestionPage.tsx
- app/src/components/Registration/theme.ts
- app/src/index.css
- app/src/index.html
- app/src/pages/ProfileEdit.tsx
Progress bar update. I'm waiting on feedback from Carolanne and Xio.
I added the Roboto font and made it the primary font throughout the site.
I added the viewport meta tag to display on mobile better.
> font, style, and progress bar updates

- app/src/components/HostFormDetail/HostFormAddress.tsx
- app/src/components/HostFormDetail/HostFormGender.tsx
- app/src/components/HostFormDetail/HostFormInfo.tsx
- app/src/components/UploadImage/UploadImageButton.tsx
Upload image component good to go
Just need the API wrapper stuff and we are all set
> Upload image component regarding issue #221

- app/src/Routes.tsx
- app/src/components/Header/Header.tsx
- app/src/data/caseworker-context.tsx
- app/src/pages/CaseworkerDashboard/CaseworkerDashboard.tsx
- blueprints/case.py
- data/repositories.py
Everything is good
I just have to Talk to Tyler about a few things
> Caseworkercontext

- docs/Makefile
- docs/make.bat
- docs/source/blueprints.rst
- docs/source/conf.py
- docs/source/config.rst
- docs/source/data.rst
- docs/source/hosthome.rst
- docs/source/index.rst
- docs/source/matching.rst
- docs/source/modules.rst
- docs/source/wsgi.rst
- hosthome.py
- requirements.txt
Adding docs and doc generation support for backend python code.
> Docs for backend

- .github/ISSUE_TEMPLATE/blank-issue.md
- .github/ISSUE_TEMPLATE/onboarding.md
Created a template for creating issues to track new member on boarding.
> Member Onboarding Issue Template

- api/README.md
- api/openapi_server/_spec/openapi.yaml
- api/openapi_server/openapi/openapi.yaml
- api/openapi_server/openapi/paths/auth/authGoogle.yaml
- api/openapi_server/openapi/paths/host.yaml
Adds in missing specifications to broken out yaml files 
Recompiles generated specification
Adds section to README about how to recompile specification
> Updates openapi yaml specification

- app/src/components/common/Header.tsx
- app/src/components/common/index.ts
- app/src/main.tsx
- app/src/services/auth.ts
- app/src/views/Home.tsx
- app/src/views/SignIn.tsx
- app/src/views/SignUp.tsx
Created a new header and added it to home, login and sign up pages
> New header to access login and sign up pages

- app/src/views/SignIn.tsx
- app/src/views/SignUp.tsx
Add a popup when email verification link is sent upon successful sign up. Added alerts for errors when signing up or signing in.
> Email verification popup

- api/openapi_server/controllers/auth_controller.py
- api/openapi_server/controllers/security_controller.py
- app/src/app/helpers.ts
- app/src/components/authentication/SignInForm.tsx
- app/src/components/authentication/SignUpForm.tsx
- app/src/components/common/Header.tsx
- app/src/views/SignIn.tsx
- app/src/views/SignUp.tsx
This PR contains the following changes:
- Shows an alert component with a message if an error occurs during the sign up or sign in process
- Changed property on error object from description to message
- Wrote a type-safe error handling utility function
> Error handling for login and signup forms

- app/cypress/e2e/forgot-password.cy.ts
- app/package-lock.json
- app/package.json
- app/src/services/api.ts
- app/src/utils/test/handlers.ts
- app/src/utils/test/setupTests.ts
- app/src/views/ForgotPasswordCode.tsx
- app/src/views/__tests__/ForgotPasswordCode.test.tsx
This PR includes:
- Functionality allowing the user to request a new forgot password code
- An alert to notify the user of a successful or unsuccessful request
- Tests
> Resend code from code submission page

- app/src/components/__tests__/SignInForm.test.tsx
- app/src/components/authentication/SignInForm.tsx
- app/src/theme/overrides/index.ts
- app/src/views/SignIn.tsx
This PR includes the following updates:
- Refactored the sign in page in accordance with the updated designs in Figma
- Updated the sign in form tests
- Removed some custom styling overrides for MUI components, but left the files as an example for the future
> Update sign in form styles

- app/src/components/authentication/NewPasswordForm.tsx
- app/src/main.tsx
- app/src/services/auth.ts
- app/src/views/NewPassword.tsx
- app/src/views/index.ts
This PR is for the new password page:
- Session_id and user_id are consumed from the URL
- API endpoints are added for the new password request
- Question: Is the password validation component also required for this page?
> New password

- app/src/components/__tests__/SignInForm.test.tsx
- app/src/components/authentication/SignInForm.tsx
- app/src/views/SignIn.tsx
Currently there aren't any loading states when a user was signing in, so this PR adds a spinner and disables the submit button when making a request either with email and password or with Google.
> Sign in loading states

- api/openapi_server/controllers/auth_controller.py
- api/requirements.txt
- app/src/components/authentication/SignInForm.tsx
- app/src/components/authentication/SignUpForm.tsx
- app/src/components/common/PasswordValidation.tsx
- app/src/services/auth.ts
- app/src/views/EmailVerificationError.tsx
- app/src/views/EmailVerificationSuccess.tsx
- app/src/views/ResetPassword.tsx
- app/src/views/SelectAccountType.tsx
- app/src/views/SignIn.tsx
- app/src/views/SignUp.tsx
Apologies ahead of time since this includes a lot of different style adjustments while preparing for the section 1 demo, and is a bit all over the place.
The main parts are:
- Updating the styling for the Sign Up form and page components
- Adding disable state to sign in form submit button before there the form is valid
- Adding the password validation component to the reset password page
- Refactoring the password validation component to work with the confirm new password input. This is a quick and dirty solution and could probably be improved.
- Navigating users to the dashboard when signed in
- Updating the layout for the email verification pages
> Style adjustments in preparation for section 1

- app/src/components/common/AuthenticatedHeader.tsx
- app/src/components/layout/DashboardLayout.tsx
- app/src/views/GuestApplicationTracker.tsx
This PR contains the following changes:
- Creates the responsive layout and headers for the dashboard home page
Closes [#571](https://github.com/hackforla/HomeUniteUs/issues/571)
https://github.com/hackforla/HomeUniteUs/assets/27253583/2955cbf7-afe6-47c0-939c-89fde690c76e
> Dashboard home page

- app/cypress.config.ts
- app/cypress/e2e/sign-up.cy.ts
- app/cypress/e2e/test-authentication.cy.ts
- app/package-lock.json
- app/src/components/authentication/SignUpForm.tsx
- app/src/components/authentication/__tests__/SignUpForm.test.tsx
- app/src/services/auth.ts
- app/src/utils/PasswordValidationSchema.tsx
- app/src/views/SignUp.tsx
Closes #660 
- Added fields for first and last name to sign up form
- Update validation schema for first and last name
- Updated requests to `signup/host` and `signup/coordinator` to include firstName and lastName properties
- Updated request types for services
- Wrote unit tests for sign up form and e2e tests testing happy path of signing up
- The only changes made to `app/cypress/e2e/test-authentication.cy.ts` were solely prettier formatting
- We need to collect first and last names when a user is created in order to properly display their names
- Wrote unit and e2e tests
<details>
<summary>Visuals before changes are applied</summary>
</details>
<details>
<summary>Visuals after changes are applied</summary>
</details>
> Collect first and last names

- .github/workflows/run-tests.yml
Closes #666 
- Removed running tests on push in gitHub actions 
- GitHub did not run any tests on push when I pushed my commit
> removed push: from github actions to only run on pull requests instead
